final: prev:
{ xterm = prev.xterm.overrideAttrs (old: {
    configureFlags = [
      ############################
      # Compile/Install Options: #
      ############################
      # "--disable-full-tgetent"
      # "--with-app-class=XXX"
      "--with-app-defaults=$(out)/lib/X11/app-defaults" # nix default
      # "--with-icon-name=XXXX"
      # "--with-icon-symlink=XXX"
      # "--with-pixmapdir=DIR"
      # "--with-icondir=DIR"
      # "--with-icon-theme=XXX"
      "--disable-desktop"
      # "--with-desktop-category=XXX"
      # "--with-reference=XXX"
      # "--with-xterm-symlink=XXX"
      # "--disable-openpty"
      # "--disable-setuid"
      # "--disable-setgid"
      # "--with-setuid=XXX"
      # "--with-utmp-setgid=XXX"
      # "--with-utempter"
      # "--with-utmp-path=XXX"
      # "--with-wtmp-path=XXX"
      "--with-tty-group=tty"        # nix default
      "--with-x"
      # "--with-pkg-config{=path}"
      # "--with-xpm=DIR"
      "--without-xinerama"
      # "--with-Xaw3d"
      # "--with-Xaw3dxft"
      # "--with-neXtaw"
      # "--with-XawPlus"
      "--disable-xcursor"
      "--enable-narrowproto"
      # "--disable-imake"
      # "--with-man2html=XXX"
      ###########################
      # Terminal Configuration: #
      ###########################
      # "--with-terminal-id=vt420"
      # "--with-terminal-type=xterm"
      "--enable-backarrow-key"
      "--enable-backarrow-is-erase"
      "--enable-delete-is-del"
      "--enable-pty-erase"
      "--enable-alt-sends-esc"
      "--enable-meta-sends-esc"
      # "--with-own-terminfo=P"
      # "--enable-env-terminfo"
      ######################
      # Optional Features: #
      ######################
      # "--disable-active-icon"
      # "--disable-ansi-color"
      # "--disable-16-color"
      # "--disable-256-color"
      # "--disable-direct-color"
      # "--disable-88-color"
      # "--disable-blink-cursor"
      "--enable-broken-osc"
      # "--disable-broken-st"
      "--enable-builtin-xpms"
      # "--disable-c1-print"
      # "--disable-bold-color"
      # "--disable-color-class"
      # "--disable-color-mode"
      # "--disable-highlighting"
      # "--disable-doublechars"
      # "--disable-boxchars"
      # "--disable-exec-selection"
      "--enable-exec-xterm"
      "--enable-double-buffer"
      # "--disable-freetype"
      "--with-freetype-config"
      "--with-freetype-cflags"
      "--with-freetype-libs"
      "--enable-hp-fkeys"
      "--enable-sco-fkeys"
      # "--disable-sun-fkeys"
      # "--disable-fifo-lines"
      # "--disable-i18n"
      # "--disable-initial-erase"
      # "--disable-input-method"
      "--enable-load-vt-fonts" # nix default
      "--enable-logging"
      "--enable-logfile-exec"
      # "--disable-maximize"
      # "--disable-num-lock"
      # "--disable-paste64"
      # "--disable-pty-handshake"
      # "--disable-readline-mouse"
      # "--disable-regex"
      # "--with-pcre2"
      # "--with-pcre"
      # "--disable-rightbar"
      # "--disable-samename"
      # "--disable-selection-ops"
      # "--disable-session-mgt"
      "--enable-status-line"
      # "--disable-tcap-fkeys"
      # "--disable-tcap-query"
      # "--disable-tek4014"
      "--enable-toolbar"
      # "--disable-vt52"
      # "--disable-wide-attrs"
      # "--disable-wide-chars"
      "--enable-16bit-chars"
      "--enable-mini-luit" # nix default
      # "--disable-luit"
      "--enable-dabbrev"
      "--enable-dec-locator"
      # "--disable-screen-dumps"
      "--enable-regis-graphics" # nix default
      # "--disable-sixel-graphics"
      # "--disable-print-graphics"
      # "--disable-rectangles"
      # "--disable-ziconbeep"
    ]; #  ++ lib.optional enableDecLocator "--enable-dec-locator";
  });
}
